### ISSUE TITLE
channel of channelList

### ISSUE THREAD

**Issue by Lucas-W** [discord-js/discord.js#13] opened 2015-08-20 12:21 UTC
I'm not sure if it's a bug in the code from a Discord update or Azure, but I'm getting this error when I try to run any of the examples/etc.

````javascript
D:\home\site\wwwroot\index.js:243
		for ( channel of channelList ) {
		              ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by hydrabolt** [comment] 2015-08-20 15:44
As discussed on Discord, this is most likely caused by an older version of node. I'll look into backwards compatibility in the future, but for now please upgrade your node version. I'll close this issue so others can now refer if they ever encounter it.

**Closed by hydrabolt** 2015-08-20 15:44 UTC
